use crate::maple::cpu::ExecutionResult;

pub mod branch_instruction;
pub mod branch_link_instruction;
pub mod compare_float_instruction;
pub mod compare_int_instruction;
pub mod compare_results_instruction;
pub mod condition_options;
pub mod conditional_branch_instruction;
pub mod conditional_skip_instruction;
pub mod exit_instruction;
pub mod float_math_instructions;
pub mod instructions;
pub mod integer_math_instructions;
pub mod io_read_write_instruction;
pub mod load_register_instruction;
pub mod logical_operations_instruction;
pub mod logical_shift_instruction;
pub mod move_instructions;
pub mod pop_push_instruction;
pub mod return_from_interrupt_instruction;
pub mod software_interrupt_instruction;
pub mod store_memory_instruction;
