pub const INTERRUPT_CODE_INVALID_INTERRUPT_CODE: u16 = 0;
pub const INTERRUPT_CODE_INVALID_DIVISION_BY_ZERO: u16 = 1;
pub const INTERRUPT_CODE_INVALID_OPCODE: u16 = 2;
pub const INTERRUPT_CODE_TIMEOUT: u16 = 3;
pub const INTERRUPT_CODE_PAGE_FAULT: u16 = 4;
pub const INTERRUPT_CODE_ILLEGAL_REGISTER_MODIFICATION: u16 = 5;
pub const INTERRUPT_CODE_ILLEGAL_DIRECT_ARGUMENT: u16 = 6;
pub const INTERRUPT_CODE_ILLEGAL_EXIT: u16 = 7;
