pub const INTERRUPT_CODE_INVALID_INTERRUPT_CODE: u32 = 0;
pub const INTERRUPT_CODE_INVALID_DIVISION_BY_ZERO: u32 = 1;
pub const INTERRUPT_CODE_INVALID_OPCODE: u32 = 2;
pub const INTERRUPT_CODE_TIMEOUT: u32 = 3;
pub const INTERRUPT_CODE_PAGE_FAULT: u32 = 4 as u32;
