#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct InstructionDetails {
    pub opcode: u64,
    pub option: u64,
}

impl InstructionDetails {
    pub const fn new(opcode: u64, option: u64) -> Self {
        Self { opcode, option }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Instruction {
    NOP,
    MOV,
    MVN,
    ADDI,
    SUBI,
    MULI,
    DIVI,
    ADDF,
    SUBF,
    MULF,
    DIVF,
    SGE,
    SEQ,
    SNE,
    SNQ,
    SGT,
    SLT,
    SLE,
    CMPI,
    CMPF,
    RGE,
    RLE,
    REQ,
    RNQ,
    RGT,
    RLT,
    BGE,
    BLE,
    BEG,
    BEQ,
    BNQ,
    BNE,
    BGT,
    BLT,
    B,
    BR,
    BL,
    LSL,
    LSR,
    AND,
    ORR,
    XOR,
    LDR,
    STR,
    POP,
    PUSH,
    EXIT,
    IOR,
    IOW,
    SWI,
    RFI,
}

impl Instruction {
    pub const fn details(&self) -> InstructionDetails {
        match self {
            Self::NOP => InstructionDetails::new(0x00, 0),
            Self::MOV => InstructionDetails::new(0x01, 0),
            Self::MVN => InstructionDetails::new(0x01, 1),
            Self::ADDI => InstructionDetails::new(0x02, 0),
            Self::SUBI => InstructionDetails::new(0x03, 0),
            Self::MULI => InstructionDetails::new(0x04, 0),
            Self::DIVI => InstructionDetails::new(0x05, 0),
            Self::ADDF => InstructionDetails::new(0x06, 0),
            Self::SUBF => InstructionDetails::new(0x07, 0),
            Self::MULF => InstructionDetails::new(0x08, 0),
            Self::DIVF => InstructionDetails::new(0x09, 0),
            Self::SGE => InstructionDetails::new(0x0A, 4),
            Self::SEQ => InstructionDetails::new(0x0A, 0),
            Self::SNE => InstructionDetails::new(0x0A, 1),
            Self::SNQ => InstructionDetails::new(0x0A, 1),
            Self::SGT => InstructionDetails::new(0x0A, 2),
            Self::SLT => InstructionDetails::new(0x0A, 3),
            Self::SLE => InstructionDetails::new(0x0A, 5),
            Self::CMPI => InstructionDetails::new(0x0B, 0),
            Self::CMPF => InstructionDetails::new(0x0C, 0),
            Self::RGE => InstructionDetails::new(0x0D, 4),
            Self::RLE => InstructionDetails::new(0x0D, 5),
            Self::REQ => InstructionDetails::new(0x0D, 0),
            Self::RNQ => InstructionDetails::new(0x0D, 1),
            Self::RGT => InstructionDetails::new(0x0D, 2),
            Self::RLT => InstructionDetails::new(0x0D, 3),
            Self::BGE => InstructionDetails::new(0x0E, 4),
            Self::BLE => InstructionDetails::new(0x0E, 5),
            Self::BEG => InstructionDetails::new(0x0E, 4),
            Self::BEQ => InstructionDetails::new(0x0E, 0),
            Self::BNQ => InstructionDetails::new(0x0E, 1),
            Self::BNE => InstructionDetails::new(0x0E, 1),
            Self::BGT => InstructionDetails::new(0x0E, 2),
            Self::BLT => InstructionDetails::new(0x0E, 3),
            Self::B => InstructionDetails::new(0x0F, 0),
            Self::BR => InstructionDetails::new(0x0F, 0),
            Self::BL => InstructionDetails::new(0x10, 0),
            Self::LSL => InstructionDetails::new(0x11, 0),
            Self::LSR => InstructionDetails::new(0x11, 1),
            Self::AND => InstructionDetails::new(0x12, 0),
            Self::ORR => InstructionDetails::new(0x12, 1),
            Self::XOR => InstructionDetails::new(0x12, 2),
            Self::LDR => InstructionDetails::new(0x13, 0),
            Self::STR => InstructionDetails::new(0x14, 0),
            Self::POP => InstructionDetails::new(0x15, 0),
            Self::PUSH => InstructionDetails::new(0x15, 1),
            Self::EXIT => InstructionDetails::new(0x16, 0),
            Self::IOR => InstructionDetails::new(0x17, 0),
            Self::IOW => InstructionDetails::new(0x17, 1),
            Self::SWI => InstructionDetails::new(0x18, 0),
            Self::RFI => InstructionDetails::new(0x19, 0),
        }
    }
}

pub fn instruction_from_name(name: String) -> Option<Instruction> {
    match name.to_uppercase().as_str() {
        "NOP" => Some(Instruction::NOP),
        "MOV" => Some(Instruction::MOV),
        "MVN" => Some(Instruction::MVN),
        "ADDI" => Some(Instruction::ADDI),
        "SUBI" => Some(Instruction::SUBI),
        "MULI" => Some(Instruction::MULI),
        "DIVI" => Some(Instruction::DIVI),
        "ADDF" => Some(Instruction::ADDF),
        "SUBF" => Some(Instruction::SUBF),
        "MULF" => Some(Instruction::MULF),
        "DIVF" => Some(Instruction::DIVF),
        "SGE" => Some(Instruction::SGE),
        "SEQ" => Some(Instruction::SEQ),
        "SNE" => Some(Instruction::SNE),
        "SNQ" => Some(Instruction::SNQ),
        "SGT" => Some(Instruction::SGT),
        "SLT" => Some(Instruction::SLT),
        "SLE" => Some(Instruction::SLE),
        "CMPI" => Some(Instruction::CMPI),
        "CMPF" => Some(Instruction::CMPF),
        "RGE" => Some(Instruction::RGE),
        "RLE" => Some(Instruction::RLE),
        "REQ" => Some(Instruction::REQ),
        "RNQ" => Some(Instruction::RNQ),
        "RGT" => Some(Instruction::RGT),
        "RLT" => Some(Instruction::RLT),
        "BGE" => Some(Instruction::BGE),
        "BLE" => Some(Instruction::BLE),
        "BEG" => Some(Instruction::BEG),
        "BEQ" => Some(Instruction::BEQ),
        "BNQ" => Some(Instruction::BNQ),
        "BNE" => Some(Instruction::BNE),
        "BGT" => Some(Instruction::BGT),
        "BLT" => Some(Instruction::BLT),
        "B" => Some(Instruction::B),
        "BR" => Some(Instruction::BR),
        "BL" => Some(Instruction::BL),
        "LSL" => Some(Instruction::LSL),
        "LSR" => Some(Instruction::LSR),
        "AND" => Some(Instruction::AND),
        "ORR" => Some(Instruction::ORR),
        "XOR" => Some(Instruction::XOR),
        "LDR" => Some(Instruction::LDR),
        "STR" => Some(Instruction::STR),
        "POP" => Some(Instruction::POP),
        "PUSH" => Some(Instruction::PUSH),
        "EXIT" => Some(Instruction::EXIT),
        "IOR" => Some(Instruction::IOR),
        "IOW" => Some(Instruction::IOW),
        "SWI" => Some(Instruction::SWI),
        "RFI" => Some(Instruction::RFI),
        _ => None,
    }
}
